import { defineConfig } from 'cz-git';

export default defineConfig({
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'revert', 'chore'],
    ],
  },
  prompt: {
    alias: { fd: 'docs: fix typos' },
    messages: {
      type: '选择你要提交的类型 | Select the type of change:',
      scope: '选择提交范围（可选） | Select a scope (optional):',
      customScope: '输入自定义范围 | Input a custom scope:',
      subject: '填写简短精炼的变更描述 | Write a short description of the change:\n',
      body: '填写详细变更描述（可选） | Write a more detailed description (optional), use "|" for new lines:\n',
      breaking: '列举不兼容的重大变更（可选） | List any breaking changes (optional), use "|" for new lines:\n',
      footerPrefixesSelect: '选择关联 issue 前缀（可选） | Select issue prefix (optional):',
      customFooterPrefix: '输入自定义 issue 前缀 | Input custom issue prefix:',
      footer: '列举关联 issue (可选) 例如: #31, #I3244 | List associated issues (optional):\n',
      confirmCommit: '是否提交该 commit | Do you want to commit?',
    },
    types: [
      { value: 'feat', name: 'feat: 新增功能 | A new feature' },
      { value: 'fix', name: 'fix: 修复缺陷 | A bug fix' },
      { value: 'docs', name: 'docs: 文档更新 | Documentation only changes' },
      { value: 'style', name: 'style: 修改样式 | Changes that do not affect the meaning of the code' },
      { value: 'refactor', name: 'refactor: 代码重构 | A code change that neither fixes a bug nor adds a feature' },
      { value: 'perf', name: 'perf: 性能优化 | A code change that improves performance' },
      { value: 'test', name: 'test: 测试相关 | Adding missing tests or correcting existing tests' },
      { value: 'chore', name: 'chore: 其他修改 | Other changes that do not modify src or test files' },
      { value: 'build', name: 'build: 打包 | Changes that affect the build system or external dependencies' },
      { value: 'ci', name: 'ci: CI 相关 | Changes to our CI configuration files and scripts' },
      { value: 'revert', name: 'revert: 回滚 | Reverts a previous commit' },
    ],
    useEmoji: false,
    emojiAlign: 'left',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: null,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [{ value: 'closed', name: 'closed: ISSUES has been processed' }],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
});
